
export const HIDE_TOAST = 'HIDE_TOAST';
export const SHOW_TOAST = 'SHOW_TOAST';
export const SET_CURRENT_TAB = 'SET_CURRENT_TAB';

export const UPDATE_ITINERARY_EVENTS_REQUEST = 'UPDATE_ITINERARY_EVENTS_REQUEST';
export const UPDATE_ITINERARY_EVENTS_FAILURE = 'UPDATE_ITINERARY_EVENTS_FAILURE';
export const UPDATE_ITINERARY_EVENTS_SUCCESS = 'UPDATE_ITINERARY_EVENTS_SUCCESS';
export const ITINERARY_RESET = 'ITINERARY_RESET';
export const UPDATE_ITINERARY_CURRENT_EVENT = 'UPDATE_ITINERARY_CURRENT_EVENT';
export const SET_ITINERARY_EVENTS = 'SET_ITINERARY_EVENTS';

export const UPDATE_GEOFENCES_REQUEST = 'UPDATE_GEOFENCES_REQUEST';
export const UPDATE_GEOFENCES_FAILURE = 'UPDATE_GEOFENCES_FAILURE';
export const UPDATE_GEOFENCES_SUCCESS = 'UPDATE_GEOFENCES_SUCCESS';
export const RESET_GEOFENCES = 'RESET_GEOFENCES';
export const UPDATE_GEOFENCE_CURRENT_ID = 'UPDATE_GEOFENCE_CURRENT_ID';
export const SET_GEOFENCES = 'SET_GEOFENCES';